package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
	"github.com/vtbarreto/CLinicius/internal/discovery"
	"gopkg.in/yaml.v3"
)

var (
	initOutput string
	initForce  bool
	initDryRun bool
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a clinicius.yaml by scanning the project structure",
	Long: `Walks the current directory looking for well-known layer folder names
and generates a clinicius.yaml with sensible default rules.

Recognized folder names:
  handler, handlers, controller, controllers, http, rest, grpc, api
  domain, core, model, entity
  usecase, usecases, service, services, application
  repository, repositories, repo, store
  infra, infrastructure, database, db, cache

Examples:
  clinicius init
  clinicius init --dry-run
  clinicius init --output configs/clinicius.yaml
  clinicius init --force`,
	RunE: runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)
	initCmd.Flags().StringVarP(&initOutput, "output", "o", "clinicius.yaml", "Output file path")
	initCmd.Flags().BoolVar(&initForce, "force", false, "Overwrite existing config file")
	initCmd.Flags().BoolVar(&initDryRun, "dry-run", false, "Print the generated config without writing it")
}

type layerYAML struct {
	Name   string   `yaml:"name"`
	Path   string   `yaml:"path"`
	Forbid []string `yaml:"forbid,omitempty"`
}

type configYAML struct {
	Layers []layerYAML `yaml:"layers"`
}

func runInit(_ *cobra.Command, _ []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}

	result, err := discovery.Discover(cwd)
	if err != nil {
		return fmt.Errorf("scanning project: %w", err)
	}

	if len(result.Layers) == 0 {
		fmt.Println("No known layer directories found.")
		fmt.Println("Organize your code into folders like handler/, domain/, repository/, infra/, usecase/")
		fmt.Println("then run clinicius init again.")
		return nil
	}

	cfg := configYAML{}
	for _, l := range result.Layers {
		cfg.Layers = append(cfg.Layers, layerYAML{
			Name:   l.Name,
			Path:   l.Path,
			Forbid: l.Forbid,
		})
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("generating YAML: %w", err)
	}

	header := "# Generated by clinicius init — review and adjust as needed.\n\n"
	content := append([]byte(header), data...)

	if initDryRun {
		fmt.Print(string(content))
		return nil
	}

	if !initForce {
		if _, err := os.Stat(initOutput); err == nil {
			return fmt.Errorf("%q already exists — use --force to overwrite", initOutput)
		}
	}

	if err := os.WriteFile(initOutput, content, 0o644); err != nil {
		return fmt.Errorf("writing %q: %w", initOutput, err)
	}

	fmt.Printf("✅ Generated %s with %d layer(s) detected:\n\n", initOutput, len(result.Layers))
	for _, l := range result.Layers {
		fmt.Printf("  %-12s  %s\n", l.Name, l.Path)
		for _, f := range l.Forbid {
			fmt.Printf("  %-12s  forbids: %s\n", "", f)
		}
	}
	fmt.Println()
	fmt.Println(strings.Repeat("-", 50))
	fmt.Println("Review the generated file, then run:")
	fmt.Println("  clinicius check ./...")

	return nil
}
